# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30578ade9e840fb11863359b817bafee7d87d7af501294337706c8c5d9b81d7855890b48091e4d56824d9edc19f57d72f3145ab9986572b023f57531ce5b9832

test:
  secret_key_base: 30d4951ada9a41c0572a6b0397bdb1ae1f1fdc465a3e0a33d37ed49b357bfc1123d8fdd0ed131d2ad384be6e8463e5df0a0e07d734eef448cd8a14ed385f527b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
